config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Timetracker::Application.routes.draw do
  resources :clients
  constraints(SubdomainPresent) do
    root 'projects#index', as: :subdomain_root
    devise_for :users
    resources :users, only: :index
    resources :projects, except: [:index, :show, :destroy]

    devise_scope :user do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    resources :companies
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                        exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

private
  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord

  validates :company_name, presence: true, uniqueness: true
  validates :company_contact_person, :company_city, :company_street_address1, :company_street_address2, :company_state, :company_phone_number, :company_email, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :client, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:new, :create]

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Database.create(@account.subdomain)
      Apartment::Database.switch(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end

private
  def account_params
    params.require(:account).permit(:subdomain, owner_attributes: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :load_schema, :authenticate_user!, :set_mailer_host
#  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

 # def configure_permitted_parameters
  #  devise_parameter_sanitizer.for(:accept_invitation).concat([:name])
 # end

  private

  def load_schema
    Apartment::Tenant.switch('public')
    return unless request.subdomain.present?

    if current_account
      Apartment::Tenant.switch(current_account.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def current_account
    @current_account ||= Account.find_by(subdomain: request.subdomain)
  end
  helper_method :current_account

  def set_mailer_host
    subdomain = current_account ? "#{current_account.subdomain}." : ""
    ActionMailer::Base.default_url_options[:host] = "#{subdomain}lvh.me:3000"
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_invite_path_for(resource)
    users_path
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:client_organization_name, :client_email, :client_organization_person_name, :client_organization_phone, :client_personal_mobile, :client_organization_street_address1, :client_organization_street_address2, :client_organization_city, :internal_notes)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit(:company_name, :company_contact_person, :company_city, :company_street_address1, :company_street_address2, :company_city_zipcode, :company_state, :company_phone_number, :company_cin, :company_vat, :company_bank_info, :company_email)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path, notice: "Project created!"
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to root_path, notice: "Project updated!"
    else
      render :edit
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :client, :archived)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_status(user)
    if current_account.owner == user || user.invitation_accepted?
      content_tag(:span, '', class: 'glyphicon glyphicon-ok color-success')
    else
      'Invitation Pending'
    end
  end
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Create an Account</h2>

    <%= simple_form_for @account do |f| %>
      <%= f.fields_for :owner do |o| %>
        <%= o.input :name %>
        <%= o.input :email %>
        <%= o.input :password %>
      <% end %>

      <%= f.input :subdomain do %>
        <div class="input-group">
          <%= f.input_field :subdomain, class: 'form-control' %>
          <span class="input-group-addon">.timetracker.dev</span>
        </div>
      <% end %>
      <%= f.button :submit, class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :client_organization_name %>
    <%= f.input :client_email %>
    <%= f.input :client_organization_person_name %>
    <%= f.input :client_organization_phone %>
    <%= f.input :client_personal_mobile %>
    <%= f.input :client_organization_street_address1 %>
    <%= f.input :client_organization_street_address2 %>
    <%= f.input :client_organization_city %>
    <%= f.input :internal_notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Client organization name</th>
      <th>Client email</th>
      <th>Client organization person name</th>
      <th>Client organization phone</th>
      <th>Client personal mobile</th>
      <th>Client organization street address1</th>
      <th>Client organization street address2</th>
      <th>Client organization city</th>
      <th>Internal notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.client_organization_name %></td>
        <td><%= client.client_email %></td>
        <td><%= client.client_organization_person_name %></td>
        <td><%= client.client_organization_phone %></td>
        <td><%= client.client_personal_mobile %></td>
        <td><%= client.client_organization_street_address1 %></td>
        <td><%= client.client_organization_street_address2 %></td>
        <td><%= client.client_organization_city %></td>
        <td><%= client.internal_notes %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client organization name:</strong>
  <%= @client.client_organization_name %>
</p>

<p>
  <strong>Client email:</strong>
  <%= @client.client_email %>
</p>

<p>
  <strong>Client organization person name:</strong>
  <%= @client.client_organization_person_name %>
</p>

<p>
  <strong>Client organization phone:</strong>
  <%= @client.client_organization_phone %>
</p>

<p>
  <strong>Client personal mobile:</strong>
  <%= @client.client_personal_mobile %>
</p>

<p>
  <strong>Client organization street address1:</strong>
  <%= @client.client_organization_street_address1 %>
</p>

<p>
  <strong>Client organization street address2:</strong>
  <%= @client.client_organization_street_address2 %>
</p>

<p>
  <strong>Client organization city:</strong>
  <%= @client.client_organization_city %>
</p>

<p>
  <strong>Internal notes:</strong>
  <%= @client.internal_notes %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/companies/_form.html.copy.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_for @company, :html => {:novalidate => "", :multipart => true} do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name, 'Company Name' %>
    <%= f.text_field :company_name, :placeholder => "Company Name", :class => "form-control focus" %>
  </div>

  <div class="form-group">
    <%= f.label :company_contact_person, 'Owner Name' %>
    <%= f.text_field :company_contact_person, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_person_title %>
    <%= f.text_field :contact_person_title %>
  </div>

  <div class="form-group">
    <%= f.label :company_city, 'City' %>
    <%= f.text_field :company_city, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_street_address1, 'Street Address 1' %>
    <%= f.text_field :company_street_address1, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_street_address2, 'Street Address 2' %>
    <%= f.text_field :company_street_address2, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_state, 'State' %>
    <%= f.text_field :company_state, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_city_zipcode, 'Pin Code' %>
    <%= f.text_field :company_city_zipcode, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_phone_number, 'Phone Number' %>
    <%= f.text_field :company_phone_number, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_email, 'Company Email ID' %>
    <%= f.text_field :company_email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_cin, 'Company CIN' %>
    <%= f.text_field :company_cin, :placeholder => "Company Registration Number", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_vat, 'VAT Registration Number' %>
    <%= f.text_field :company_vat, :placeholder => "VAT Registration Number", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company_bank_info, 'Company Bank A/c Detail' %>
    <%= f.text_area :company_bank_info, :placeholder => "Bank Info for your customer to enable him to Bank transfer Payment. Will be printed in Invoice", :class => 'col-md-6 form-control', :rows => '3' %>
  </div>
<br>
<br>  
  <div class="form-group actions">
    <%= f.submit 'Save', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Company name</th>
        <th>Company City</th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.company_name %></td>
          <td><%= company.company_city %></td>
          <td><%= link_to 'See Details', company %></td>
          <td><%= link_to 'Edit Company Details', edit_company_path(company) %></td>
          <td><%= button_to 'Delete Company', company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="container-fluid">
<p id="notice", class ="bg-success"> <%= notice %></p>
<div class="well company-show-page">
<p>
  <strong>Company name:</strong>
  <%= @company.company_name.titleize %>
</p>

<p>
  <strong>Company Contact Name:</strong>
  <%= @company.company_contact_person.capitalize %>
</p>

<p>
  <strong>Company Address:</strong>
  <%= @company.company_street_address1 %>, <%= @company.company_street_address2 %>,
  <%= @company.company_city %>
</p>

<p> <strong>Company Contact Number:</strong>
  <%= @company.company_phone_number %>
</p>

<p>
	<strong>
		Company Email ID:
	</strong>
	<%= @company.company_email %>
</p>

<p>
	<strong>
		Company CIN Regsitration Number:
	</strong>
	<%= @company.company_cin %>
</p>

<p>
	<strong>
		Company VAT Registration Number:
	</strong>
	<%= @company.company_vat %>
</p>

<p>
	<strong>
		Company A/c Bank Info: 
	</strong>
	<%= @company.company_bank_info %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
</div>
</div>

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= render 'layouts/bootstrap' %>

   <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="container">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <%= link_to 'Time Tracker', root_path, class: 'navbar-brand' %>
    </div>
    <% if user_signed_in? %>
      <div class="pull-right right-buttons">
        <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Project', new_project_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
    <% end %>
  </nav>
</header>

<div class="container">
			<% flash.each do |name, msg| %>
				<% if msg.is_a?(String) %>
					<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable fade in">
					<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
					</div>
				<% end %>
			<% end %>

  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project,
                    wrapper_mappings: { boolean: :vertical_boolean }) do |f| %>

  <%= f.input :name %>
  <%= f.input :client %>

  <% if @project.persisted? %>
    <%= f.input :archived, as: :boolean %>
  <% end %>
  
  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Update Project</h2>
    <%= render "form" %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="col-md-12">
  <% @projects.each do |project| %>
    <h3>
      <%= project.name %>
      <small><%= project.client %></small>
      <div class="pull-right">
        <%= link_to edit_project_path(project), class: "icon-link" do %>
          <small><i class="glyphicon glyphicon-cog"></i></small>
        <% end %>
        <small><i class="glyphicon glyphicon-plus-sign"></i></small>
      </div>
    </h3>

    <ul class="list-group">
      <li class="list-group-item">No entries yet!</li>
    </ul>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>New Project</h2>
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>Authorized Users</h2>

  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user_status(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <h3 class="extra-margin-top">Invite User</h3>

      <%= simple_form_for(User.new, url: user_invitation_path,
                                    html: { class: 'form-inline' }) do |f| %>
        <%= f.input :email, placeholder: 'Email', label: false %>
        <%= f.button :submit, 'Invite User', class: 'btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <h1>Time Tracker</h1>
    <p>Track your time with the most awesome time tracking app ever.</p>
    <p><%= link_to "Create Account", new_account_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
</div>